//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMicroServicio.PruebaTutorialServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PruebaTutorialServicio.IServicioPrueba")]
    public interface IServicioPrueba {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrueba/cargaPruebaExcel", ReplyAction="http://tempuri.org/IServicioPrueba/cargaPruebaExcelResponse")]
        void cargaPruebaExcel(System.IO.FileStream file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrueba/cargaPruebaExcel", ReplyAction="http://tempuri.org/IServicioPrueba/cargaPruebaExcelResponse")]
        System.Threading.Tasks.Task cargaPruebaExcelAsync(System.IO.FileStream file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrueba/enviarCorreo", ReplyAction="http://tempuri.org/IServicioPrueba/enviarCorreoResponse")]
        string enviarCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPrueba/enviarCorreo", ReplyAction="http://tempuri.org/IServicioPrueba/enviarCorreoResponse")]
        System.Threading.Tasks.Task<string> enviarCorreoAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPruebaChannel : PruebaMicroServicio.PruebaTutorialServicio.IServicioPrueba, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPruebaClient : System.ServiceModel.ClientBase<PruebaMicroServicio.PruebaTutorialServicio.IServicioPrueba>, PruebaMicroServicio.PruebaTutorialServicio.IServicioPrueba {
        
        public ServicioPruebaClient() {
        }
        
        public ServicioPruebaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPruebaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPruebaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPruebaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void cargaPruebaExcel(System.IO.FileStream file) {
            base.Channel.cargaPruebaExcel(file);
        }
        
        public System.Threading.Tasks.Task cargaPruebaExcelAsync(System.IO.FileStream file) {
            return base.Channel.cargaPruebaExcelAsync(file);
        }
        
        public string enviarCorreo(string correo) {
            return base.Channel.enviarCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<string> enviarCorreoAsync(string correo) {
            return base.Channel.enviarCorreoAsync(correo);
        }
    }
}
